### PR TITLE
Use cluster health check to make sure new index template can be created.

### PR DESCRIPTION
**Pull request by lukas-vlcek**
May be we can replace hardcoded `sleep 5` with Elasticsearch [cluster health](https://www.elastic.co/guide/en/elasticsearch/reference/1.5/cluster-health.html) check?

However, is [this line](https://github.com/BitScoutOrg/docker-elasticsearch/blob/master/run-container.sh#L22) in [run-container.sh](https://github.com/BitScoutOrg/docker-elasticsearch/blob/master/run-container.sh) related in any way? If yes, is proposed change going to have any impact then?

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
I think I understand better now what was the original idea behind `sleep 5` command. Correct me if I am wrong but it should simply give Elasticsearch enough time to startup. Which means my change will probably not work correctly because doing `curl localhost:9200` right away might fail because Elasticsearch did not have enough time to start up yet.

So, I think what we can do is to keep `wait 5` for now and add the cluster health check right after it. The idea of cluster health check is to make sure cluster is stable enough for pushing index templates in. I will update my PR.

**Comment by richm** [comment]
Yeah, any sleep or wait in that script is a hack.  Yes, we need a better mechanism to know when elasticsearch is available for index template requests.

**Comment by lukas-vlcek** [comment]
@richm right. Do you think my PR makes any sense then? I mean, shall we merge it or just close?
I think proposed change can be handy in situation when ES is already started (after initial 5 sec wait) and can accept HTTP requests but the cluster has not yet fully formed or there is something else going on in it that makes pushing index template highly risky (the state of cluster is red). In such case it gives us additional 5 sec for the cluster to stabilise (and we can prolong this interval if we want).
Do you think this can be useful?

**Comment by richm** [comment]
Yes, the PR makes sense, but please do this:
1) remove the sleep 5
2) make the timeout much longer, 30 seconds
3) add the error handling

**Comment by lukas-vlcek** [comment]
@richm 
As for 1) and 2): We need to distinguish two cases: a) Elasticsearch process not being ready to accept calls on port, b) Elasticsearch search not being ready to accept index mappings yet.

As for 3): I am not sure how exactly should be errors handled in context of Docker run script. Do you know what are the best practices? I added some `exit 1` commands but other than this I am opened to suggestions.

I did the following updates: I added `wait_for_port_open` function which tries to connect to Elasticsearch port for 30 seconds and fails if not. Then I use the same timeout value (i.e. 30 sec) to wait until the Elasticsearch health status is at least yellow. Errors from this second call are not handled yet (this would probably require processing of JSON response in shell... not sure I know elegant way ATM).

**Comment by lukas-vlcek** [comment]
Also I think this PR targets #7 as well.

**Comment by richm** [comment]
Looks good.  Will remove #7

**Pull request merged**
